on:
  push:
    branches: [dev]

name: Deploy Client to Dev Server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${{ github.ref_name }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSHKEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /Users/${{ secrets.USERNAME }}/Documents/Mine/github-action-guide
            git pull
